server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlite::resource:db/covszp.db
    #url: jdbc:sqlite:C:/sqlite/covszp.db
    #url: jdbc:sqlite:data/covszp.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    
  #热部署生效
  devtools:
    restart:
      enabled: true
          
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/,classpath:/static/#模板加载路径 按需配置
    charset: UTF-8 #编码格式    
    settings:
       number_format: '0.##'   #数字格式化，无小数点
#mybatis
mybatis:
    mapperLocations: classpath:mappers/*.xml
    

 
